### ISSUE TITLE
BUG :: Compiler must enforce that overriden message field is of same base mixin

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjc-php#40]
Overriding a field currently enforces that types are the same.  However, when a schema overrides a message type field, the underlying constraint (the curie(s)) allows for a variation which could lead to bugs and incompatible schemas.

Example, `gdbots:ncr:mixin:create-node` requires a `node` field to be a `gdbots:ncr:mixin:node`.  it would be ideal in a concrete message to enforce a particular node type on an overridden field.

this needs to take into account the "any of" of course.

this update would allow for builtin constraints that still validate in mixins and makes library development simpler.

let's discuss before you start.

**Comment by gdbrown** [comment]
the field override is also not enforcing that the "rule" is the same.  i can override a map to any other rule.  that part is definitely a bug.

**Comment by excelwebzone** [comment]
## Overridable:

```xml
<!-- 1-0-0 -->
<field name="test_message" type="message" overridable="true">
  <any-of>
    <curie>acme:core::test-message</curie>
  </any-of>
</field>
```

```xml
<!-- 1-0-1 -->
<field name="test_message" type="message" overridable="true">
  <any-of>
    <curie>acme:blog:entity:article</curie>
  </any-of>
</field>
```

thrown exception:

```
Fatal error: Uncaught exception 'Gdbots\Pbjc\Exception\ValidatorException' with message 'The schema "pbj:acme:core:mixin:entity:1-0-1" field "test_message" must include the following anyOf class(es): "acme:core::test-message".' in /../gdbots/pbjc-php/src/Validator/FieldMustContainsAnyOfClasses.php:43 Stack trace: #0 /../gdbots/pbjc-php/src/SchemaValidator.php(66): Gdbots\Pbjc\Validator\FieldMustContainsAnyOfClasses->validate(Object(Gdbots\Pbjc\SchemaDescriptor), Object(Gdbots\Pbjc\SchemaDescriptor)) #1 /../gdbots/pbjc-php/src/Compiler.php(74): Gdbots\Pbjc\SchemaValidator->validate(Object(Gdbots\Pbjc\SchemaDescriptor)) #2 /../gdbots/pbjc-php/examples/web/compiler.php(20): Gdbots\Pbjc\Compiler->__construct() #3 {main} thrown in /../gdbots/pbjc-php/src/Validator/FieldMustContainsAnyOfClasses.php on line 43
```

## Rule:

```xml
<!-- 1-0-0 -->
<field name="thumbnails" type="string" format="url" rule="map" />
```

```xml
<!-- 1-0-1 -->
<field name="thumbnails" type="string" format="url" rule="set" />
```

thrown exception:

```
Fatal error: Uncaught exception 'Gdbots\Pbjc\Exception\ValidatorException' with message 'The schema "pbj:acme:core:mixin:entity:1-0-1" field "thumbnails" should be of rule "map".' in /../gdbots/pbjc-php/src/Validator/FieldAttributeEqualTo.php:65 Stack trace: #0 /../gdbots/pbjc-php/src/SchemaValidator.php(66): Gdbots\Pbjc\Validator\FieldAttributeEqualTo->validate(Object(Gdbots\Pbjc\SchemaDescriptor), Object(Gdbots\Pbjc\SchemaDescriptor)) #1 /../gdbots/pbjc-php/src/Compiler.php(74): Gdbots\Pbjc\SchemaValidator->validate(Object(Gdbots\Pbjc\SchemaDescriptor)) #2 /../gdbots/pbjc-php/examples/web/compiler.php(20): Gdbots\Pbjc\Compiler->__construct() #3 {main} thrown in /../gdbots/pbjc-php/src/Validator/FieldAttributeEqualTo.php on line 65
```

**Comment by gdbrown** [comment]
ran a test with multiple any-of...
```
Fatal error: Cannot declare class GdbotsNcrNodeV100, because the name is already in use in /Users/greg/www/schemas/gdbots-schemas/vendor/gdbots/pbjc/src/Validator/SchemaInheritanceFields.php(108) : eval()'d code on line 4
PHP Fatal error:  Cannot declare class GdbotsNcrNodeV100, because the name is already in use in /Users/greg/www/schemas/gdbots-schemas/vendor/gdbots/pbjc/src/Validator/SchemaInheritanceFields.php(108) : eval()'d code on line 4
```
